name: Quality check and Publish package to GitHub Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches: '*'

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@werchethandb'
          
      - name: Experiment
      - run: |
            npm build
            ls -alrt
            find /home/runner/work/chethan-trial-1/chethan-trial-1/ -name "*.tgz"        

#  - name: build
#         run: |
#           pwd             # /home/runner/work/chethan-trial-1/chethan-trial-1
#           npm build
#           ls -alrt
#           cd ./dist/components-lib
#           pwd             # /home/runner/work/chethan-trial-1/chethan-trial-1/dist/components-lib
#           ls -alrt
#           npm pack

  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [quality]
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@werchethandb'
      - run: |
          pwd             # /home/runner/work/chethan-trial-1/chethan-trial-1
          npm build
          ls -alrt
          cd ./dist/components-lib
          pwd             # /home/runner/work/chethan-trial-1/chethan-trial-1/dist/components-lib
          ls -alrt
          npm pack
          npm publish

        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
